In [1]:
#NumPy 

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
#This is 1-D Array

In [8]:
my_mat = [[1,2,3],[4,5,6]]

In [9]:
arr1 = np.array(my_mat)

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
#NumPy Inbuilt Fuction to Create Arrays

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(2)

array([ 0.,  0.])

In [15]:
np.zeros(2,2)

TypeError: data type not understood

In [16]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [17]:
np.ones(1)

array([ 1.])

In [18]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [4]:
np.linspace(0,10)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [20]:
np.linspace(1,10,5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [21]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.random.rand(5)

array([ 0.33649371,  0.15617162,  0.63988714,  0.91125016,  0.90411046])

In [23]:
np.random.rand(5,5)

array([[ 0.48840956,  0.02410742,  0.140543  ,  0.30236778,  0.43090754],
       [ 0.95551196,  0.27375097,  0.92065872,  0.03300373,  0.02203076],
       [ 0.97083889,  0.05098198,  0.25386445,  0.14488253,  0.28283905],
       [ 0.993901  ,  0.57725076,  0.5865632 ,  0.4715999 ,  0.58443282],
       [ 0.00774661,  0.87744509,  0.77612478,  0.67702612,  0.80662177]])

In [27]:
np.random.randn(2,10)
#Normal Distribution

array([[-0.77766448, -0.26473242, -0.58370785,  0.6126674 , -0.55050819,
         0.09165394,  2.67795916,  0.13888155,  0.57297613,  0.54544621],
       [ 0.17473136,  2.29080815,  1.10754365,  0.26251891,  1.2212554 ,
         0.17705092, -1.06349774,  0.52824321,  0.24995566, -0.07478206]])

In [28]:
np.random.randint(1,10)

5

In [29]:
np.random.randint(1,10,10)

array([8, 4, 3, 8, 1, 5, 7, 9, 7, 3])

In [30]:
from numpy.random import randint

In [31]:
arr = randint(1,10,10)

In [32]:
arr.shape

(10,)

In [33]:
arr.reshape(2,5)

array([[3, 5, 6, 6, 7],
       [3, 7, 9, 8, 9]])

In [34]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [35]:
arr.max()

9

In [36]:
arr.min()

3

In [37]:
arr.argmax()

7

In [38]:
arr.argmin()

0

In [40]:
arr.dtype

dtype('int32')

In [41]:
#NumPy Indexing 

In [51]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[1]

1

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[0:4] = 100

In [50]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr = arr[0:5]

In [54]:
slice_of_arr[:]


array([0, 1, 2, 3, 4])

In [55]:
slice_of_arr[:] = 99 

In [56]:
slice_of_arr[:]

array([99, 99, 99, 99, 99])

In [57]:
arr[:]

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [58]:
 arr_cp = arr.copy()

In [59]:
arr_cp[:] = 101

In [60]:
arr_cp[:]

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [61]:
arr[:]

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [63]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [64]:
arr_2d[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr_2d[0][0]
#Double Bracket Format

1

In [68]:
arr_2d[0,0]
#Single Bracket Format

1

In [69]:
a = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [70]:
a[1:,1:]

array([[25, 30],
       [40, 45]])

In [71]:
b = np.arange(0,11)

In [72]:
b > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [73]:
b[bool_arg]

NameError: name 'bool_arg' is not defined

In [74]:
array[bool_arg]

NameError: name 'array' is not defined

In [75]:
bool_arg = b > 5

In [76]:
bool_arg

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [77]:
b[bool_arg]

array([ 6,  7,  8,  9, 10])

In [78]:
b[b>4]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
arr = np.arange(50).reshape(5,10)

In [80]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
arr[1,1:3]

array([11, 12])

In [84]:
#NumPy Operations

In [103]:
a = np.arange(1,11)

In [104]:
b = np.arange(2,12)

In [87]:
c = a + b

In [88]:
c

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [89]:
c = a - b

In [90]:
c

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [91]:
c = a*b

In [92]:
c

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [93]:
c = a + 100

In [94]:
c

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [95]:
c = a / b

In [96]:
c

array([ 0.5       ,  0.66666667,  0.75      ,  0.8       ,  0.83333333,
        0.85714286,  0.875     ,  0.88888889,  0.9       ,  0.90909091])

In [97]:
a[0] = 0

In [98]:
b/a

C:\Users\YASH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.5       ,  1.33333333,  1.25      ,  1.2       ,
        1.16666667,  1.14285714,  1.125     ,  1.11111111,  1.1       ])

In [99]:
a/b

array([ 0.        ,  0.66666667,  0.75      ,  0.8       ,  0.83333333,
        0.85714286,  0.875     ,  0.88888889,  0.9       ,  0.90909091])

In [100]:
a / b

array([ 0.        ,  0.66666667,  0.75      ,  0.8       ,  0.83333333,
        0.85714286,  0.875     ,  0.88888889,  0.9       ,  0.90909091])

In [101]:
1 / b

array([ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667,
        0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909])

In [102]:
1 / a

C:\Users\YASH\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
        0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ])

In [105]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766])

In [106]:
np.exp(b)

array([  7.38905610e+00,   2.00855369e+01,   5.45981500e+01,
         1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
         2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
         5.98741417e+04])

In [107]:
np.max(a)

10

In [108]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [109]:
np.log(b)

array([ 0.69314718,  1.09861229,  1.38629436,  1.60943791,  1.79175947,
        1.94591015,  2.07944154,  2.19722458,  2.30258509,  2.39789527])

In [110]:
#----END-----